add sonarcloud coverage
gaepdit/app-library pull request #10
Opened 2022-10-11 14:28 UTC by patdnr

2022-10-11 14:47 UTC, patdnr commented
Running the same command locally gives result, while Github Actions does not produce any.
![image](https://user-images.githubusercontent.com/113926513/195123726-8d3c0d50-18c4-43bc-aea4-522fe40d84a2.png)

![image](https://user-images.githubusercontent.com/113926513/195123601-64f78621-1682-4f99-a180-5c26a61fed88.png)

2022-10-11 14:48 UTC, patdnr commented
See gaepdit/EPD-IT#82

2022-10-11 20:25 UTC, dougwaldron requested changes
I see you were having trouble getting coverlet to work. I'm pretty sure it was just a typo (see code comment below). 

When I use the dotnet-coverage command you currently have, I get a lot of extraneous results (see screenshot), plus error messages when using report generator. 
![image](https://user-images.githubusercontent.com/737326/195191330-744fc89e-1128-4e62-ad0a-dd488dc202a8.png)


You could probably get it to work with some additional tweaking, but it's probably easier to go back to coverlet.

2022-10-14 01:43 UTC, patdnr commented on .github/workflows/sonarcloud-scan.yml
>            coverlet .\tests\bin\Debug\net6.0\GaEpd.AppLibrary.Tests.dll --target "dotnet" --targetargs "test --no-build" -f=opencover -o="coverage.xml"
I have changed the argument to what you have suggested, as well as following other arguments that worked for other people but they all did not work. This post (https://github.com/coverlet-coverage/coverlet/issues/575) is very closely related to the current issue.

2022-10-14 20:47 UTC, dougwaldron commented
It looks like your latest commit is working. I tried getting coverlet to work as well and got the same result as you: The command works fine when run locally but returns no results on GitHub. But since you got this other method to work, it's not worth pursuing.

One question though. Is the trx logger option still needed or was that just for testing? If it's not needed, please remove, and I'll merge this on Monday. Thanks for your great work on this!

2022-10-14 21:56 UTC, patdnr commented
the result-directory option used to require the logger option to work (https://stackoverflow.com/questions/49390416/dotnet-test-not-creating-test-results-folder). I have tested it locally, and it is not needed anymore.

2022-10-17 12:54 UTC, dougwaldron commented
> the result-directory option used to require the logger option to work (https://stackoverflow.com/questions/49390416/dotnet-test-not-creating-test-results-folder). I have tested it locally, and it is not needed anymore.

Ok, thanks. I was wondering if it was something like that.

2022-10-17 12:55 UTC, dougwaldron approved these changes

2022-10-17 12:56 UTC, merged